### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by vymak** [inteve/simple-image-storage#1]
Please fix PHP 7.2 compatibility for this component. Main problem is used **extends \Nette\Object** in ImageStorage.php, because Object could not be used as name in PHP 7.2

**Comment by janpecha** [comment]
Hi, thanks for report, please try current `dev-master`, if it will be ok, I tag new version.

**Comment by janpecha** [comment]
I just released version 2.0.0, it fixes this issue.
